namespace Healthcare.Application.DTOs;

/// <summary>
/// Data Transfer Object for Appointment entity.
/// </summary>
public sealed class AppointmentDto
{
    public int Id { get; set; }

    /// <summary>
    /// Unique reference code — generated by Singleton pattern.
    /// Format: APT-YYYYMMDD-XXXX
    /// </summary>
    public string ReferenceCode { get; set; } = string.Empty;

    /// <summary>Patient ID — used by AppointmentFacade lightweight mapping.</summary>
    public int PatientId { get; set; }

    /// <summary>Doctor ID — used by AppointmentFacade lightweight mapping.</summary>
    public int DoctorId { get; set; }

    public PatientDto Patient { get; set; } = null!;
    public DoctorDto Doctor { get; set; } = null!;

    public DateTime ScheduledTime { get; set; }
    public string ScheduledDate { get; set; } = string.Empty;
    public string ScheduledTimeFormatted { get; set; } = string.Empty;
    public string Status { get; set; } = string.Empty;
    public string Reason { get; set; } = string.Empty;
    public string? DoctorNotes { get; set; }
    public string? CancellationReason { get; set; }

    /// <summary>Fee amount.</summary>
    public decimal ConsultationFeeAmount { get; set; }

    /// <summary>Fee currency.</summary>
    public string ConsultationFeeCurrency { get; set; } = string.Empty;

    public DateTime? ConfirmedAt { get; set; }
    public DateTime? CompletedAt { get; set; }
    public DateTime? CancelledAt { get; set; }
    public DateTime CreatedAt { get; set; }
}
