using Healthcare.Domain.Entities;
using Healthcare.Domain.Enums;
using Healthcare.Domain.ValueObjects;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Healthcare.Adapters.Persistence.EntityFramework.Configurations;

/// <summary>
/// Entity Framework configuration for Appointment entity.
/// Indexes are aligned to real repository filters and sort orders.
/// </summary>
public class AppointmentConfiguration : IEntityTypeConfiguration<Appointment>
{
    // AppointmentStatus enum values stored as int
    private const int StatusPending = (int)AppointmentStatus.Pending;
    private const int StatusConfirmed = (int)AppointmentStatus.Confirmed;

    public void Configure(EntityTypeBuilder<Appointment> builder)
    {
        builder.ToTable("Appointments");

        builder.HasKey(a => a.Id);

        builder.HasOne(a => a.Patient)
            .WithMany()
            .HasForeignKey(a => a.PatientId)
            .OnDelete(DeleteBehavior.Restrict);

        builder.HasOne(a => a.Doctor)
            .WithMany()
            .HasForeignKey(a => a.DoctorId)
            .OnDelete(DeleteBehavior.Restrict);

        builder.Property(a => a.ScheduledTime)
            .HasConversion(
                time => time.Value,
                // FromPersistence: do not re-validate future/advance rules on every load
                value => AppointmentTime.FromPersistence(value))
            .IsRequired()
            .HasColumnName("ScheduledTime");

        builder.Property(a => a.Status)
            .IsRequired()
            .HasConversion<int>();

        builder.Property(a => a.Reason)
            .IsRequired()
            .HasMaxLength(500);

        builder.Property(a => a.DoctorNotes)
            .HasMaxLength(2000);

        builder.Property(a => a.CancellationReason)
            .HasMaxLength(500);

        builder.Property(a => a.PaymentOverrideReason)
            .HasMaxLength(500)
            .IsRequired(false);

        builder.Property(a => a.ConfirmedAt).IsRequired(false);
        builder.Property(a => a.CompletedAt).IsRequired(false);
        builder.Property(a => a.CancelledAt).IsRequired(false);
        builder.Property(a => a.RemindedAt).IsRequired(false);

        builder.Property(a => a.IsDeleted)
            .IsRequired()
            .HasDefaultValue(false);

        builder.Property(a => a.DeletedAt).IsRequired(false);

        // Global query filter: exclude soft-deleted appointments from all queries
        builder.HasQueryFilter(a => !a.IsDeleted);

        builder.Property(a => a.CreatedAt).IsRequired();
        builder.Property(a => a.ModifiedAt).IsRequired(false);

        builder.Property<byte[]>("RowVersion")
            .IsRowVersion()
            .IsConcurrencyToken();

        builder.Property(a => a.ReferenceCode)
             .IsRequired()
             .HasMaxLength(20)
             .HasDefaultValue(string.Empty)
             .HasComment("Unique reference code generated by IAppointmentCodeGenerator");

        builder.HasIndex(a => a.ReferenceCode)
            .IsUnique()
            .HasDatabaseName("IX_Appointments_ReferenceCode");

        builder.OwnsOne(a => a.ConsultationFee, money =>
        {
            money.Property(m => m.Amount)
                .IsRequired()
                .HasColumnType("decimal(18,2)")
                .HasColumnName("ConsultationFee_Amount");

            money.Property(m => m.Currency)
                .IsRequired()
                .HasMaxLength(3)
                .HasColumnName("ConsultationFee_Currency");
        });

        // ── Indexes (query-driven) ──────────────────────────────────────────
        //
        // Removed as redundant / low value (see migration notes):
        // - IX_Appointments_DoctorId  → prefix of Doctor_Time / Doctor_Status_Time
        // - IX_Appointments_Status    → prefix of Status_Time
        // - IX_Appointments_IsDeleted → almost always filtered to 0 by global query filter
        //
        // Kept / added composites match repository WHERE + ORDER BY shapes.

        // Patient lists: WHERE PatientId = @id ORDER BY ScheduledTime DESC
        builder.HasIndex(a => new { a.PatientId, a.ScheduledTime })
            .HasDatabaseName("IX_Appointments_Patient_Time");

        // Doctor day / schedule: WHERE DoctorId = @id AND ScheduledTime BETWEEN ...
        // Named overload required so EF keeps this alongside the filtered unique index below.
        builder.HasIndex(a => new { a.DoctorId, a.ScheduledTime }, "IX_Appointments_Doctor_Time");

        // Status + time analytics / GetByStatus: WHERE Status = @s [AND time range]
        builder.HasIndex(a => new { a.Status, a.ScheduledTime }, "IX_Appointments_Status_Time");

        // Reminder job: Confirmed, future window, RemindedAt IS NULL
        // Filtered index keeps only the small "needs reminder" working set.
        builder.HasIndex(a => new { a.ScheduledTime, a.RemindedAt }, "IX_Appointments_Reminders")
            .HasFilter($"[Status] = {StatusConfirmed} AND [RemindedAt] IS NULL AND [IsDeleted] = 0");

        // Double-booking guard: one active (Pending/Confirmed) slot per doctor+time.
        // Cancelled/Completed/NoShow rows are excluded so the slot can be rebooked.
        // SQL Server filtered indexes forbid OR/IN; Status Pending=1 Confirmed=2 => [Status] <= 2.
        builder.HasIndex(a => new { a.DoctorId, a.ScheduledTime }, "IX_Appointments_Doctor_Time_Active")
            .IsUnique()
            .HasFilter($"[IsDeleted] = 0 AND [Status] <= {StatusConfirmed}");

        // Supporting index for doctor lists filtered by status (dashboards)
        builder.HasIndex(a => new { a.DoctorId, a.Status, a.ScheduledTime }, "IX_Appointments_Doctor_Status_Time");

        builder.Ignore(a => a.DomainEvents);
    }
}
