using Healthcare.Domain.Common;
using Healthcare.Domain.Enums;
using Healthcare.Domain.Events;
using Healthcare.Domain.Services;
using Healthcare.Domain.ValueObjects;

namespace Healthcare.Domain.Entities;

/// <summary>
/// Represents a medical appointment between a patient and a doctor.
/// This is an Aggregate Root in DDD terms.
/// </summary>
/// <remarks>
/// State transition rules (enforced by <see cref="EnsureCanTransitionTo"/>):
/// - Pending → Confirmed, Cancelled
/// - Confirmed → Completed, Cancelled, NoShow
/// - Completed, Cancelled, NoShow → Terminal (no further status changes)
///
/// All state changes raise domain events for the Observer pattern.
/// </remarks>
public sealed class Appointment : Entity
{
    /// <summary>
    /// Explicit allowed status transitions. Single source of truth for the state machine.
    /// Terminal statuses map to an empty set (no outbound transitions).
    /// </summary>
    private static readonly IReadOnlyDictionary<AppointmentStatus, IReadOnlySet<AppointmentStatus>> AllowedTransitions =
        new Dictionary<AppointmentStatus, IReadOnlySet<AppointmentStatus>>
        {
            [AppointmentStatus.Pending] = new HashSet<AppointmentStatus>
            {
                AppointmentStatus.Confirmed,
                AppointmentStatus.Cancelled
            },
            [AppointmentStatus.Confirmed] = new HashSet<AppointmentStatus>
            {
                AppointmentStatus.Completed,
                AppointmentStatus.Cancelled,
                AppointmentStatus.NoShow
            },
            [AppointmentStatus.Completed] = new HashSet<AppointmentStatus>(),
            [AppointmentStatus.Cancelled] = new HashSet<AppointmentStatus>(),
            [AppointmentStatus.NoShow] = new HashSet<AppointmentStatus>()
        };

    /// <summary>
    /// Statuses that allow non-terminal mutations that do not change status
    /// (e.g. reschedule). Soft-deleted appointments are blocked separately.
    /// </summary>
    private static readonly IReadOnlySet<AppointmentStatus> MutableStatuses =
        new HashSet<AppointmentStatus>
        {
            AppointmentStatus.Pending,
            AppointmentStatus.Confirmed
        };

    /// <summary>
    /// Gets the patient ID associated with this appointment.
    /// </summary>
    public int PatientId { get; private set; }

    /// <summary>
    /// Gets the patient navigation property (for EF Core).
    /// </summary>
    public Patient Patient { get; private set; } = null!;

    /// <summary>
    /// Gets the doctor ID associated with this appointment.
    /// </summary>
    public int DoctorId { get; private set; }

    /// <summary>
    /// Gets the doctor navigation property (for EF Core).
    /// </summary>
    public Doctor Doctor { get; private set; } = null!;

    /// <summary>
    /// Gets the scheduled time for this appointment.
    /// </summary>
    public AppointmentTime ScheduledTime { get; private set; } = null!;

    /// <summary>
    /// Gets the current status of this appointment.
    /// </summary>
    public AppointmentStatus Status { get; private set; }

    /// <summary>
    /// Gets the reason for the appointment.
    /// </summary>
    public string Reason { get; private set; } = string.Empty;

    /// <summary>
    /// Gets the notes added by the doctor during/after the appointment.
    /// </summary>
    public string? DoctorNotes { get; private set; }

    /// <summary>
    /// Gets the cancellation reason (if appointment was cancelled).
    /// </summary>
    public string? CancellationReason { get; private set; }

    /// <summary>
    /// Gets the date and time when the appointment was confirmed.
    /// </summary>
    public DateTime? ConfirmedAt { get; private set; }

    /// <summary>
    /// Gets the date and time when the appointment was completed.
    /// </summary>
    public DateTime? CompletedAt { get; private set; }

    /// <summary>
    /// Gets the date and time when the appointment was cancelled.
    /// </summary>
    public DateTime? CancelledAt { get; private set; }

    /// <summary>
    /// Gets the date and time when the reminder was sent for this appointment.
    /// </summary>
    public DateTime? RemindedAt { get; private set; }

    /// <summary>
    /// Gets the consultation fee for this appointment.
    /// </summary>
    public Money ConsultationFee { get; private set; } = null!;

    /// <summary>
    /// Gets the justification recorded when a Doctor/Admin confirmed this
    /// appointment despite no successful payment existing yet (business-rule
    /// override). Null when the appointment was confirmed normally.
    /// </summary>
    public string? PaymentOverrideReason { get; private set; }

    /// <summary>
    /// Gets the unique human-readable reference code for this appointment.
    /// Generated by an injected <see cref="IAppointmentCodeGenerator"/>.
    /// </summary>
    /// <remarks>
    /// Format: APT-YYYYMMDD-XXXX  (e.g., APT-20260226-0001)
    /// </remarks>
    public string ReferenceCode { get; private set; } = string.Empty;

    /// <summary>
    /// Gets whether this appointment has been soft-deleted.
    /// </summary>
    public bool IsDeleted { get; private set; }

    /// <summary>
    /// Gets the date and time when this appointment was soft-deleted.
    /// </summary>
    public DateTime? DeletedAt { get; private set; }

    // Private parameterless constructor for EF Core
    private Appointment() { }

    /// <summary>
    /// Initializes a new instance of the <see cref="Appointment"/> class.
    /// Private constructor - use Create() factory method.
    /// </summary>
    private Appointment(
        int patientId,
        int doctorId,
        AppointmentTime scheduledTime,
        string reason,
        Money consultationFee)
    {
        PatientId = patientId;
        DoctorId = doctorId;
        ScheduledTime = scheduledTime;
        Reason = reason;
        ConsultationFee = consultationFee;
        Status = AppointmentStatus.Pending;
        CreatedAt = DateTime.UtcNow;
    }

    /// <summary>
    /// Creates a new Appointment using the Factory Method pattern.
    /// </summary>
    /// <param name="patient">The patient booking the appointment.</param>
    /// <param name="doctor">The doctor for the appointment.</param>
    /// <param name="scheduledTime">The desired appointment time.</param>
    /// <param name="reason">The reason for the appointment.</param>
    /// <param name="codeGenerator">
    /// Injected service for generating unique reference codes.
    /// Must be provided by the application layer (DI); never resolved via a static Singleton.
    /// </param>
    /// <returns>A new valid Appointment entity.</returns>
    /// <remarks>
    /// Design patterns used here:
    ///   1. Factory Method → static Create() controls instantiation
    ///   2. Dependency Injection → code generator supplied by the caller
    ///   3. Guard Clauses → fail-fast validation
    /// </remarks>
    public static Appointment Create(
        Patient patient,
        Doctor doctor,
        AppointmentTime scheduledTime,
        string reason,
        IAppointmentCodeGenerator codeGenerator)
    {
        Guard.AgainstNull(patient, nameof(patient));
        Guard.AgainstNull(doctor, nameof(doctor));
        Guard.AgainstNull(scheduledTime, nameof(scheduledTime));
        Guard.AgainstNullOrWhiteSpace(reason, nameof(reason));
        Guard.AgainstNull(codeGenerator, nameof(codeGenerator));

        if (!patient.IsActive)
        {
            throw new InvalidOperationException(
                "Cannot book appointment - patient account is inactive.");
        }

        if (!doctor.IsActive)
        {
            throw new InvalidOperationException(
                "Cannot book appointment - doctor is not active.");
        }

        if (!doctor.IsAcceptingPatients)
        {
            throw new InvalidOperationException(
                "Doctor is not accepting patients.");
        }

        if (reason.Trim().Length < 10)
        {
            throw new ArgumentException(
                "Appointment reason must be at least 10 characters.", nameof(reason));
        }

        var appointment = new Appointment(
            patient.Id, doctor.Id, scheduledTime, reason.Trim(), doctor.ConsultationFee);
        appointment.Patient = patient;
        appointment.Doctor = doctor;
        appointment.ReferenceCode = codeGenerator.GenerateCode();

        appointment.AddDomainEvent(new AppointmentCreatedEvent(
            appointment.Id,
            patient.Id,
            doctor.Id,
            scheduledTime.Value));

        return appointment;
    }

    /// <summary>
    /// Confirms the appointment.
    /// </summary>
    /// <param name="paymentOverrideReason">
    /// Optional justification. Pass a non-null value ONLY when a Doctor/Admin
    /// is deliberately confirming this appointment despite payment not having
    /// succeeded yet (e.g. an emergency walk-in). Leave null for the normal
    /// flow, where payment has already succeeded.
    /// The application layer (<c>ConfirmAppointmentHandler</c>) decides
    /// WHETHER an override is allowed/required for a given appointment; this
    /// method only enforces that, IF a reason is supplied, it is meaningful.
    /// </param>
    public void Confirm(string? paymentOverrideReason = null)
    {
        EnsureCanTransitionTo(AppointmentStatus.Confirmed, "confirm");

        if (ScheduledTime.IsPast())
        {
            throw new InvalidOperationException("Cannot confirm past appointments.");
        }

        string? normalizedReason = null;
        if (!string.IsNullOrWhiteSpace(paymentOverrideReason))
        {
            normalizedReason = paymentOverrideReason.Trim();

            if (normalizedReason.Length < 10)
            {
                throw new ArgumentException(
                    "Payment override reason must be at least 10 characters.",
                    nameof(paymentOverrideReason));
            }
        }

        TransitionTo(AppointmentStatus.Confirmed);
        ConfirmedAt = DateTime.UtcNow;
        PaymentOverrideReason = normalizedReason;
        MarkAsModified();

        AddDomainEvent(new AppointmentConfirmedEvent(
            Id,
            PatientId,
            DoctorId,
            ScheduledTime.Value,
            normalizedReason));
    }

    /// <summary>
    /// Cancels the appointment.
    /// </summary>
    /// <param name="cancellationReason">The reason for cancellation.</param>
    public void Cancel(string cancellationReason)
    {
        Guard.AgainstNullOrWhiteSpace(cancellationReason, nameof(cancellationReason));
        EnsureCanTransitionTo(AppointmentStatus.Cancelled, "cancel");

        if (cancellationReason.Trim().Length < 10)
        {
            throw new ArgumentException(
                "Cancellation reason must be at least 10 characters.",
                nameof(cancellationReason));
        }

        TransitionTo(AppointmentStatus.Cancelled);
        CancellationReason = cancellationReason.Trim();
        CancelledAt = DateTime.UtcNow;
        MarkAsModified();

        AddDomainEvent(new AppointmentCancelledEvent(
            Id,
            PatientId,
            DoctorId,
            ScheduledTime.Value,
            CancellationReason));
    }

    /// <summary>
    /// Marks the appointment as completed with doctor's notes.
    /// </summary>
    /// <param name="doctorNotes">Notes added by the doctor.</param>
    public void Complete(string doctorNotes)
    {
        Guard.AgainstNullOrWhiteSpace(doctorNotes, nameof(doctorNotes));
        EnsureCanTransitionTo(AppointmentStatus.Completed, "complete");

        if (doctorNotes.Trim().Length < 20)
        {
            throw new ArgumentException(
                "Doctor notes must be at least 20 characters.",
                nameof(doctorNotes));
        }

        TransitionTo(AppointmentStatus.Completed);
        DoctorNotes = doctorNotes.Trim();
        CompletedAt = DateTime.UtcNow;
        MarkAsModified();

        AddDomainEvent(new AppointmentCompletedEvent(
            Id,
            PatientId,
            DoctorId,
            ScheduledTime.Value));
    }

    /// <summary>
    /// Marks the appointment as a no-show (patient didn't arrive).
    /// </summary>
    public void MarkAsNoShow()
    {
        EnsureCanTransitionTo(AppointmentStatus.NoShow, "mark as no-show");

        if (!ScheduledTime.IsPast())
        {
            throw new InvalidOperationException(
                "Cannot mark as no-show before the scheduled time.");
        }

        TransitionTo(AppointmentStatus.NoShow);
        MarkAsModified();

        AddDomainEvent(new AppointmentNoShowEvent(
            Id,
            PatientId,
            DoctorId,
            ScheduledTime.Value));
    }

    /// <summary>
    /// Marks the appointment as having had its reminder sent.
    /// Also sets RemindedAt even when notification delivery was skipped
    /// (e.g. patient disabled email), so the background job doesn't
    /// reprocess the same appointment on every tick.
    /// </summary>
    public void MarkReminderSent()
    {
        EnsureNotDeleted();
        RemindedAt = DateTime.UtcNow;
        MarkAsModified();
    }

    /// <summary>
    /// Reschedules the appointment to a new time.
    /// Allowed only while the appointment is Pending or Confirmed.
    /// </summary>
    /// <param name="newScheduledTime">The new appointment time.</param>
    public void Reschedule(AppointmentTime newScheduledTime)
    {
        Guard.AgainstNull(newScheduledTime, nameof(newScheduledTime));
        EnsureMutable("reschedule");

        if (newScheduledTime == ScheduledTime)
        {
            throw new InvalidOperationException(
                "New appointment time must be different from current time.");
        }

        ScheduledTime = newScheduledTime;
        MarkAsModified();
    }

    /// <summary>
    /// Applies a final price calculated by a pricing strategy.
    /// </summary>
    /// <remarks>
    /// Called by BookAppointmentHandler after PricingContext
    /// calculates the final price based on AppointmentType.
    ///
    /// Example:
    ///   Base fee   = $100 (from Doctor)
    ///   Strategy   = InsurancePricingStrategy (30% discount)
    ///   Final price = $70  ← stored here
    /// </remarks>
    public void ApplyPricingStrategy(decimal finalPrice, string currency)
    {
        EnsureMutable("apply pricing");

        if (finalPrice < 0)
        {
            throw new ArgumentException(
                "Price cannot be negative.", nameof(finalPrice));
        }

        ConsultationFee = Money.Create(finalPrice, currency);
        MarkAsModified();
    }

    /// <summary>
    /// Checks if the appointment needs a reminder (within 24 hours).
    /// </summary>
    public bool NeedsReminder()
    {
        return Status == AppointmentStatus.Confirmed && ScheduledTime.IsWithinNext24Hours();
    }

    /// <summary>
    /// Soft-deletes this appointment. Once deleted, it cannot be deleted again.
    /// </summary>
    public void Delete()
    {
        if (IsDeleted)
        {
            throw new InvalidOperationException("This appointment has already been deleted.");
        }

        IsDeleted = true;
        DeletedAt = DateTime.UtcNow;
        MarkAsModified();
    }

    /// <summary>
    /// Checks if the appointment is terminal (no more status transitions allowed).
    /// </summary>
    public bool IsTerminal()
    {
        return AllowedTransitions.TryGetValue(Status, out var targets) && targets.Count == 0;
    }

    /// <summary>
    /// Returns the set of statuses that may be reached from the current status.
    /// Empty for terminal statuses.
    /// </summary>
    public IReadOnlySet<AppointmentStatus> GetAllowedTransitions()
    {
        return AllowedTransitions.TryGetValue(Status, out var targets)
            ? targets
            : new HashSet<AppointmentStatus>();
    }

    /// <summary>
    /// Enforces the explicit state machine before any status-changing operation.
    /// Soft-deleted appointments cannot transition.
    /// </summary>
    private void EnsureCanTransitionTo(AppointmentStatus targetStatus, string operation)
    {
        EnsureNotDeleted();

        if (!AllowedTransitions.TryGetValue(Status, out var allowed) ||
            !allowed.Contains(targetStatus))
        {
            throw new InvalidAppointmentStateException(operation, Status.ToString());
        }
    }

    /// <summary>
    /// Enforces that the appointment is in a non-terminal, non-deleted state
    /// for mutations that do not change status (reschedule, pricing).
    /// </summary>
    private void EnsureMutable(string operation)
    {
        EnsureNotDeleted();

        if (!MutableStatuses.Contains(Status))
        {
            throw new InvalidAppointmentStateException(operation, Status.ToString());
        }
    }

    private void EnsureNotDeleted()
    {
        if (IsDeleted)
        {
            throw new InvalidOperationException(
                "Cannot modify a soft-deleted appointment.");
        }
    }

    private void TransitionTo(AppointmentStatus targetStatus)
    {
        Status = targetStatus;
    }
}
