<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <RootNamespace>Healthcare.ArchitectureTests</RootNamespace>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="NetArchTest.Rules" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <!-- Load all production layers for dependency analysis -->
    <ProjectReference Include="..\Healthcare.Domain\Healthcare.Domain.csproj" />
    <ProjectReference Include="..\Healthcare.Application\Healthcare.Application.csproj" />
    <ProjectReference Include="..\Healthcare.Adapters\Healthcare.Adapters.csproj" />
    <ProjectReference Include="..\Healthcare.Presentation.API\Healthcare.Presentation.API.csproj" />
  </ItemGroup>

</Project>
