#!/usr/bin/env bash
# Build a Compose-compatible .env.secrets file from secrets/* files.
# Usage: ./scripts/materialize-env-secrets.sh ./secrets > .env.secrets
set -euo pipefail

DIR="${1:-./secrets}"
read_secret() {
  local f="$DIR/$1"
  if [[ -f "$f" ]]; then
    # trim CR/LF
    tr -d '\r\n' < "$f"
  fi
}

DB_PASSWORD="$(read_secret db_password)"
JWT_SECRET="$(read_secret jwt_secret)"
STRIPE_SECRET_KEY="$(read_secret stripe_secret_key)"
STRIPE_PUBLISHABLE_KEY="$(read_secret stripe_publishable_key)"
STRIPE_WEBHOOK_SECRET="$(read_secret stripe_webhook_secret)"
BOOTSTRAP_ADMIN_PASSWORD="$(read_secret bootstrap_admin_password)"

[[ -n "$DB_PASSWORD" ]] || { echo "missing $DIR/db_password" >&2; exit 1; }
[[ -n "$JWT_SECRET" ]] || { echo "missing $DIR/jwt_secret" >&2; exit 1; }
[[ ${#JWT_SECRET} -ge 32 ]] || { echo "jwt_secret must be >= 32 chars" >&2; exit 1; }

# shellcheck disable=SC2016
cat <<EOF
# Generated by materialize-env-secrets.sh — mode 600 on the server
DB_PASSWORD=${DB_PASSWORD}
JWT_SECRET=${JWT_SECRET}
STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
STRIPE_PUBLISHABLE_KEY=${STRIPE_PUBLISHABLE_KEY}
STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
BOOTSTRAP_ADMIN_PASSWORD=${BOOTSTRAP_ADMIN_PASSWORD}
EOF
