using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Healthcare.Adapters.Migrations
{
    /// <inheritdoc />
    public partial class OptimizeQueryIndexes : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropIndex(
                name: "IX_Payments_Status",
                table: "Payments");

            migrationBuilder.DropIndex(
                name: "IX_Payments_TransactionId",
                table: "Payments");

            migrationBuilder.DropIndex(
                name: "IX_OutboxMessages_ProcessedAt",
                table: "OutboxMessages");

            migrationBuilder.DropIndex(
                name: "IX_AuditLogs_Entity",
                table: "AuditLogs");

            migrationBuilder.DropIndex(
                name: "IX_AuditLogs_EntityType",
                table: "AuditLogs");

            migrationBuilder.DropIndex(
                name: "IX_Appointments_Doctor_Time",
                table: "Appointments");

            migrationBuilder.DropIndex(
                name: "IX_Appointments_DoctorId",
                table: "Appointments");

            migrationBuilder.DropIndex(
                name: "IX_Appointments_IsDeleted",
                table: "Appointments");

            migrationBuilder.DropIndex(
                name: "IX_Appointments_PatientId",
                table: "Appointments");

            migrationBuilder.DropIndex(
                name: "IX_Appointments_Status",
                table: "Appointments");

            migrationBuilder.AlterColumn<string>(
                name: "ReferenceCode",
                table: "Appointments",
                type: "nvarchar(20)",
                maxLength: 20,
                nullable: false,
                defaultValue: "",
                comment: "Unique reference code generated by IAppointmentCodeGenerator",
                oldClrType: typeof(string),
                oldType: "nvarchar(20)",
                oldMaxLength: 20,
                oldDefaultValue: "",
                oldComment: "Unique reference code generated by AppointmentCodeGenerator Singleton");

            migrationBuilder.CreateIndex(
                name: "IX_UserSessions_User_Active",
                table: "UserSessions",
                columns: new[] { "UserId", "LastUsedAt" },
                filter: "[RevokedAt] IS NULL");

            migrationBuilder.CreateIndex(
                name: "IX_Users_DoctorId",
                table: "Users",
                column: "DoctorId",
                filter: "[DoctorId] IS NOT NULL");

            migrationBuilder.CreateIndex(
                name: "IX_Users_PatientId",
                table: "Users",
                column: "PatientId",
                filter: "[PatientId] IS NOT NULL");

            migrationBuilder.CreateIndex(
                name: "IX_Users_Role",
                table: "Users",
                column: "Role");

            migrationBuilder.CreateIndex(
                name: "IX_Payments_Status_PaidAt",
                table: "Payments",
                columns: new[] { "Status", "PaidAt" });

            migrationBuilder.CreateIndex(
                name: "IX_Payments_TransactionId",
                table: "Payments",
                column: "TransactionId",
                unique: true,
                filter: "[TransactionId] IS NOT NULL");

            migrationBuilder.CreateIndex(
                name: "IX_OutboxMessages_Pending",
                table: "OutboxMessages",
                columns: new[] { "OccurredOn", "RetryCount" },
                filter: "[ProcessedAt] IS NULL");

            migrationBuilder.CreateIndex(
                name: "IX_AuditLogs_Entity_Time",
                table: "AuditLogs",
                columns: new[] { "EntityType", "EntityId", "OccurredOn" });

            // Non-unique covering schedule lookups for ALL statuses (history, cancelled, etc.)
            migrationBuilder.CreateIndex(
                name: "IX_Appointments_Doctor_Time",
                table: "Appointments",
                columns: new[] { "DoctorId", "ScheduledTime" });

            migrationBuilder.CreateIndex(
                name: "IX_Appointments_Doctor_Status_Time",
                table: "Appointments",
                columns: new[] { "DoctorId", "Status", "ScheduledTime" });

            // DB-level double-booking guard for active slots only (Pending=1, Confirmed=2)
            migrationBuilder.CreateIndex(
                name: "IX_Appointments_Doctor_Time_Active",
                table: "Appointments",
                columns: new[] { "DoctorId", "ScheduledTime" },
                unique: true,
                filter: "[IsDeleted] = 0 AND [Status] <= 2");

            migrationBuilder.CreateIndex(
                name: "IX_Appointments_Patient_Time",
                table: "Appointments",
                columns: new[] { "PatientId", "ScheduledTime" });

            migrationBuilder.CreateIndex(
                name: "IX_Appointments_Reminders",
                table: "Appointments",
                columns: new[] { "ScheduledTime", "RemindedAt" },
                filter: "[Status] = 2 AND [RemindedAt] IS NULL AND [IsDeleted] = 0");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropIndex(
                name: "IX_UserSessions_User_Active",
                table: "UserSessions");

            migrationBuilder.DropIndex(
                name: "IX_Users_DoctorId",
                table: "Users");

            migrationBuilder.DropIndex(
                name: "IX_Users_PatientId",
                table: "Users");

            migrationBuilder.DropIndex(
                name: "IX_Users_Role",
                table: "Users");

            migrationBuilder.DropIndex(
                name: "IX_Payments_Status_PaidAt",
                table: "Payments");

            migrationBuilder.DropIndex(
                name: "IX_Payments_TransactionId",
                table: "Payments");

            migrationBuilder.DropIndex(
                name: "IX_OutboxMessages_Pending",
                table: "OutboxMessages");

            migrationBuilder.DropIndex(
                name: "IX_AuditLogs_Entity_Time",
                table: "AuditLogs");

            migrationBuilder.DropIndex(
                name: "IX_Appointments_Doctor_Status_Time",
                table: "Appointments");

            migrationBuilder.DropIndex(
                name: "IX_Appointments_Doctor_Time_Active",
                table: "Appointments");

            // Up recreated Doctor_Time after dropping the old one; drop it so Down can restore cleanly.
            migrationBuilder.DropIndex(
                name: "IX_Appointments_Doctor_Time",
                table: "Appointments");

            migrationBuilder.DropIndex(
                name: "IX_Appointments_Patient_Time",
                table: "Appointments");

            migrationBuilder.DropIndex(
                name: "IX_Appointments_Reminders",
                table: "Appointments");

            migrationBuilder.AlterColumn<string>(
                name: "ReferenceCode",
                table: "Appointments",
                type: "nvarchar(20)",
                maxLength: 20,
                nullable: false,
                defaultValue: "",
                comment: "Unique reference code generated by AppointmentCodeGenerator Singleton",
                oldClrType: typeof(string),
                oldType: "nvarchar(20)",
                oldMaxLength: 20,
                oldDefaultValue: "",
                oldComment: "Unique reference code generated by IAppointmentCodeGenerator");

            migrationBuilder.CreateIndex(
                name: "IX_Payments_Status",
                table: "Payments",
                column: "Status");

            migrationBuilder.CreateIndex(
                name: "IX_Payments_TransactionId",
                table: "Payments",
                column: "TransactionId");

            migrationBuilder.CreateIndex(
                name: "IX_OutboxMessages_ProcessedAt",
                table: "OutboxMessages",
                column: "ProcessedAt");

            migrationBuilder.CreateIndex(
                name: "IX_AuditLogs_Entity",
                table: "AuditLogs",
                columns: new[] { "EntityType", "EntityId" });

            migrationBuilder.CreateIndex(
                name: "IX_AuditLogs_EntityType",
                table: "AuditLogs",
                column: "EntityType");

            migrationBuilder.CreateIndex(
                name: "IX_Appointments_Doctor_Time",
                table: "Appointments",
                columns: new[] { "DoctorId", "ScheduledTime" });

            migrationBuilder.CreateIndex(
                name: "IX_Appointments_DoctorId",
                table: "Appointments",
                column: "DoctorId");

            migrationBuilder.CreateIndex(
                name: "IX_Appointments_IsDeleted",
                table: "Appointments",
                column: "IsDeleted");

            migrationBuilder.CreateIndex(
                name: "IX_Appointments_PatientId",
                table: "Appointments",
                column: "PatientId");

            migrationBuilder.CreateIndex(
                name: "IX_Appointments_Status",
                table: "Appointments",
                column: "Status");
        }
    }
}
