<Project Sdk="Microsoft.NET.Sdk">

	<ItemGroup>
		<!-- Email Support -->
		<PackageReference Include="BCrypt.Net-Next" />
		<PackageReference Include="Konscious.Security.Cryptography.Argon2" />
		<PackageReference Include="MailKit" />
		<PackageReference Include="Microsoft.Extensions.Http" />
		

		<!-- Dependency Injection (FULL, not just Abstractions) -->
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Binder" />
		<!-- Logging (REQUIRED for ILogger<>) -->
		<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
		<PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" />
		<PackageReference Include="StackExchange.Redis" />
		<PackageReference Include="StackExchange.Redis.Extensions.Core" />
		<PackageReference Include="StackExchange.Redis.Extensions.Newtonsoft" />
		<PackageReference Include="Stripe.net" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Healthcare.Application\Healthcare.Application.csproj" />
		<ProjectReference Include="..\Healthcare.Domain\Healthcare.Domain.csproj" />
	</ItemGroup>

	<ItemGroup>
		<!-- Entity Framework Core -->
		<PackageReference Include="Microsoft.EntityFrameworkCore" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools">
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design">
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>
	</ItemGroup>

</Project>
