namespace Healthcare.Application.DTOs;

/// <summary>
/// Data Transfer Object for Appointment entity.
/// </summary>
public sealed class AppointmentDto
{
    /// <summary>Gets or sets the appointment ID.</summary>
    public int Id { get; set; }

    /// <summary>
    /// Unique human-readable reference code generated by the Singleton pattern.
    /// Format: APT-YYYYMMDD-XXXX (e.g., APT-20260226-0001)
    /// Design Pattern: Singleton (Creational) - AppointmentCodeGenerator.Instance
    /// </summary>
    public string ReferenceCode { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the patient ID (used by AppointmentFacade lightweight mapping).
    /// </summary>
    public int PatientId { get; set; }

    /// <summary>
    /// Gets or sets the doctor ID (used by AppointmentFacade lightweight mapping).
    /// </summary>
    public int DoctorId { get; set; }

    /// <summary>Gets or sets the full patient object.</summary>
    public PatientDto Patient { get; set; } = null!;

    /// <summary>Gets or sets the full doctor object.</summary>
    public DoctorDto Doctor { get; set; } = null!;

    /// <summary>Gets or sets the scheduled date and time.</summary>
    public DateTime ScheduledTime { get; set; }

    /// <summary>Gets or sets the scheduled date (formatted yyyy-MM-dd).</summary>
    public string ScheduledDate { get; set; } = string.Empty;

    /// <summary>Gets or sets the scheduled time formatted for display.</summary>
    public string ScheduledTimeFormatted { get; set; } = string.Empty;

    /// <summary>Gets or sets the appointment status.</summary>
    public string Status { get; set; } = string.Empty;

    /// <summary>Gets or sets the reason for the appointment.</summary>
    public string Reason { get; set; } = string.Empty;

    /// <summary>Gets or sets the doctor's notes (if completed).</summary>
    public string? DoctorNotes { get; set; }

    /// <summary>Gets or sets the cancellation reason (if cancelled).</summary>
    public string? CancellationReason { get; set; }

    /// <summary>Gets or sets the consultation fee amount (full mapping).</summary>
    public decimal ConsultationFeeAmount { get; set; }

    /// <summary>Gets or sets the consultation fee currency (full mapping).</summary>
    public string ConsultationFeeCurrency { get; set; } = string.Empty;

    /// <summary>Gets or sets the consultation fee amount (Facade lightweight mapping).</summary>
    public decimal ConsultationFee { get; set; }

    /// <summary>Gets or sets the currency (Facade lightweight mapping).</summary>
    public string Currency { get; set; } = string.Empty;

    /// <summary>Gets or sets when the appointment was confirmed.</summary>
    public DateTime? ConfirmedAt { get; set; }

    /// <summary>Gets or sets when the appointment was completed.</summary>
    public DateTime? CompletedAt { get; set; }

    /// <summary>Gets or sets when the appointment was cancelled.</summary>
    public DateTime? CancelledAt { get; set; }

    /// <summary>Gets or sets when the appointment was created.</summary>
    public DateTime CreatedAt { get; set; }
}